### ISSUE TITLE
todo-ignore is ignored on journal pages that were created from templates

### ISSUE THREAD

**Issue by BreiteSeite** [ahonn/logseq-plugin-todo#63]
Steps to reproduce:

1. create a template that includes that `todo-ignore: true` property as part of the template content (not to confuse with template properties) which contains TODO items
2. set the template as journal template in `config.edn`
```
 :default-templates
 {:journals "Template name here"}
```
3. let logseq create todays journal page (ensure `todo-ignore: true` is at the beginning of the journal page)

Expected output:
- TODO items are not listed in the plugin

Actual output:
- TODO items are listed in the plugin (as scheduled as well as anytime)

Workaround:
- update the property manually on the generated journal page

**Comment by ahonn** [comment]
This seems to be a bug in Logseq. When you use a template to create a journal page automatically, the properties are not parsed correctly. However, this issue is resolved when you reopen Logseq. 

I have found an alternative workaround for it, so please update to the latest version. If you have any questions, just let me know.

If you like this plugin, feel free to show your appreciation by [buying me a coffee](https://www.buymeacoffee.com/yuexunjiang). It will motivate me to continue maintaining it.
