### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by m1ome** [ahonn/logseq-plugin-todo#64]
**Steps to reproduce:**
1. Install Logseq
2. Open plugin manager
3. Install plugin
4. Click on the plugin icon

**Expected behaviour:**
Opened a window with a todo list.

**Actual behaviour:**
Nothing happens, at all.

**Debug information:**
Logseq version: Version 0.10.2 (76)
Logseq os: MacOS
Console errors 

```
Uncaught (in promise) Error: Not existed method #queryElementRect
    at br.R (lsplugin.core.js:2:49378)
    at br.<anonymous> (lsplugin.core.js:2:93271)
    at a.emit (lsplugin.core.js:2:28521)
    at X.<anonymous> (lsplugin.core.js:2:88623)
    at lsplugin.core.js:2:53506
    at Array.forEach (<anonymous>)
    at X.listener (lsplugin.core.js:2:53491)
    at g (helpers.js:151:57)
```

Code it refers to
```js
    async function $h() {
        const e = await logseq.App.queryElementRect("#" + Mi.id) // <- this string as i understand
          , t = document.querySelector("#" + Mi.id);
        Object.assign(t.style, {
            position: "fixed",
            top: `${e.top + 40}px`,
            left: e.left + "px"
        }),
        logseq.showMainUI()
    }
```

**Comment by fabri-alare** [comment]
It happens to me to some days ago was working
now nothing happens

**Comment by dag2108** [comment]
Also no longer working for me since update to version 10.2

**Comment by SM-26** [comment]
Also stopped working for me after updating to 0.10.2
seems like we are not the only one, [Git plugin also have problems](https://github.com/logseq/logseq/issues/10743).

I would think it's because of this commit: https://github.com/logseq/logseq/pull/10399
I've tried to test it in [Desktop APP Nightly Release 20231223](https://github.com/logseq/logseq/releases/tag/nightly) but still the same problem.

Going back to 0.10.1 fix it (for now).

**Comment by ahonn** [comment]
Thanks for your feedback.
The plugin has already fixed this issue, please update to the latest version (v1.20.1).
